### ISSUE TITLE
Current methodology results in failures during cutover run

### ISSUE THREAD

**Issue by hypnoz** [pizzaops/pizzaops-cutover#1]
Here is another method of approach that may help. This person creates a bash script, and that runs once puppet completes it's run. This avoid puppet killing self halfway through it's current run. It also has logic for only running the clean action once.

https://stuckinadoloop.wordpress.com/2012/02/16/automated-migration-of-systems-to-a-new-puppet-master-server/

Sorry if this isn't the right place to post this, I couldn't find a better place for posting this info.

**Comment by big-samantha** [comment]
Is there any specific reason you have for wanting it to work that way? To date I haven't really seen many issues with just blowing things away in the middle and causing some failures. The only real issue is that you end up with no report getting submitted to the old master, and I do suppose that would be nice...but since the report wouldn't contain anything about removing the `ssldir` anyway, I'm not sure how useful it would really be.

Thoughts, @hypnoz?

**Comment by big-samantha** [comment]
I'm going to close this for now because I don't really see much benefit to it, but I'm willing to be convinced otherwise.
