### ISSUE TITLE
clean puppet certs

### ISSUE THREAD

**Issue by brettswift** [pizzaops/pizzaops-cutover#5]
This is not a trivial inclusion to this module, but to keep things clean, it'd be nice to remove the cert off the old puppet master. 

This would be the most complicated thing here, as there would have to be an exported resource or something like that to trigger an event on the puppet master...   somehow to run `puppet cert clean x`. 

With enough nodes, this could end up with a bunch of orphaned certs..   unless you had another process in mind (other than manual!)

**Comment by big-samantha** [comment]
@brettswift sorry for the delay, I'm finally returning to working on this.

That being said, I'm not sure I want to do this, because the use case here is for migrating off an old Puppet infrastructure to a new one, permanently. It would also hugely increase the complexity of what's being done, since it's now a multi-node operation. E.g. for each puppet run that performs this task, we have to do something on the target node AND the CA.

Thoughts?

**Comment by brettswift** [comment]
I know the complexity is big.  The main interest is licensing with PE, as when you migrate without cleaning certs you're still using that extra license. 

I've actually taken a different route - but it's not ready for open source yet..  some tight coupling to our private infrastructure. 

The way I've been doing it is with an mcollective agent.   I find it's easier to do that than to run agents on environments.. especially for PE users like us that have environments classified in the console..  you'd also have to keep rebasing your cutover branch to apply nodes. 

Basically the mco agent I have has a syntax where you just have to pass it the new puppet master.  The v3 to 2015.x  is a bit sledge-hammery,  in that it uninstalls puppet completely. 

From puppet4 to puppet4 master I have yet to write the code but we need to do a few specific things like change /etc/hosts entries (so the pe yum repo works), clean certs, and re-run the agent.

I'd love to get this module out into the community if there's interest.  I know you guys ilkely have this cutover module working well for you.   Do you see an mcollective agent helping your workflow at all?

**Comment by big-samantha** [comment]
Hmm, I'd be interested to know more. An mco agent could be interesting, since doing this outside of a puppet run removes some of the complexity and "gotchas" people can run into.

I'm also curious why the licensing thing is an issue - e.g. the whole point of this for me is moving off of an old infrastructure, not keeping both around, so it doesn't really matter to me what the licensing count is.

Also, recent versions of PE (I think including 3.8) do not count licenses based on certs signed, but on "active" nodes in PuppetDB.

**Comment by brettswift** [comment]
Ok well I don't know if it'll be for a few weeks - right now I'm trying to get some beaker tests on ec2 working for a bunch of our modules. 

I'll make a point of getting this out there.   I'd love feedback,  and of course contributions. :)

**Comment by big-samantha** [comment]
@brettswift sounds good. Feel free to shoot me an email at myname @ puppetlabs.com.

My name is "Zee".

The awkward phrasing of this comment brought to you by "trying to avoid spammers".
